
/*5. Do the following :

5a. Create a function to sum two numbers and return the value. 

5b. Create a function to generate a random number between 0 to 10

5c. Pass two values to the sum function, But first value should be 
    passed by the user and the second value should be generated by a 
    random function*/



var a = 10;
//5a. Creating a function to return a random variable
let random = function () {
    return Math.floor(Math.random() * 10)
}
//5b. Creating a function to return sum.
function sum(x,y){
    return(x+y)

}
//5c. passing the valuse of user and randomly generated variable.
console.log(sum(a,random()))